print('Hello world!')
print('What is your name?')
myname = input()
print('Its nice to meet you, ' + myname)
print('The length of your name is : ')
print(len(myname))
print('What is your age?')
myage = input()
print('you will be ' +str(int(myage)+1) + ' in a year.')
