baconfile = open('bacon.txt', 'w')
baconfile.write('Hello world!\n')
baconfile.close()
baconFile = open('bacon.txt', 'a')
baconFile.write('Bacon is not a vegetable.')
baconFile.close()
baconFile = open('bacon.txt')
content = baconFile.read()
baconFile.close()
print(content)